# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 321e2df48e86f6439dfbcf1711df17538be99fdc911b7b446094f22dc7aa118bc87777b0db51c4604cb1e4291f4375e6b55f7b48b5a943516f122086f1455800

test:
  secret_key_base: 2f52f7810e43c53e50392480df01bae4b69f457e340ba580507fcf8c044aea69db186a974122f868364246eb64de4d780bbdae4cc73e605738103033f0593c28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
